In [1]:
import nltk
import spacy
import tensorflow as tf
import datetime 
import pandas as pd
import numpy as np
import fasttext

In [2]:
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
df = pd.read_csv('D:\\HWAN\\Data\\Symptom_checker_dataset\\SymptomDisease.csv')

In [4]:
df

Unnamed: 0      label                                               text
0              0  Psoriasis  I have been experiencing a skin rash on my arm...
1              1  Psoriasis  My skin has been peeling, especially on my kne...
2              2  Psoriasis  I have been experiencing joint pain in my fing...
3              3  Psoriasis  There is a silver like dusting on my skin, esp...
4              4  Psoriasis  My nails have small dents or pits in them, and...
...          ...        ...                                                ...
1195         295   diabetes  I'm shaking and trembling all over. I've lost ...
1196         296   diabetes  Particularly in the crevices of my skin, I hav...
1197         297   diabetes  I regularly experience these intense urges and...
1198         298   diabetes  I have trouble breathing, especially outside. ...
1199         299   diabetes  I constantly sneeze and have a dry cough. My i...

[1200 rows x 3 columns]

In [5]:
df.shape

(1200, 3)

In [6]:
df = df[['label', 'text']]

In [7]:
from nltk import word_tokenize
import spacy

In [8]:
nlp = spacy.load('en_core_web_sm')

In [9]:
def tokenize(sentence):
    sentence = sentence.lower()
    doc = nlp(sentence)
    tokens = []
    for token in doc:
        if token.is_alpha:
            tokens.append(token.text)
    return tokens

In [10]:
df

label                                               text
0     Psoriasis  I have been experiencing a skin rash on my arm...
1     Psoriasis  My skin has been peeling, especially on my kne...
2     Psoriasis  I have been experiencing joint pain in my fing...
3     Psoriasis  There is a silver like dusting on my skin, esp...
4     Psoriasis  My nails have small dents or pits in them, and...
...         ...                                                ...
1195   diabetes  I'm shaking and trembling all over. I've lost ...
1196   diabetes  Particularly in the crevices of my skin, I hav...
1197   diabetes  I regularly experience these intense urges and...
1198   diabetes  I have trouble breathing, especially outside. ...
1199   diabetes  I constantly sneeze and have a dry cough. My i...

[1200 rows x 2 columns]

In [11]:
labels = {}
for i,label in enumerate(df['label']):
    labels[label] = i

In [12]:
labels

{'Psoriasis': 49,
 'Varicose Veins': 99,
 'Typhoid': 149,
 'Chicken pox': 199,
 'Impetigo': 249,
 'Dengue': 299,
 'Fungal infection': 349,
 'Common Cold': 399,
 'Pneumonia': 449,
 'Dimorphic Hemorrhoids': 499,
 'Arthritis': 549,
 'Acne': 599,
 'Bronchial Asthma': 649,
 'Hypertension': 699,
 'Migraine': 749,
 'Cervical spondylosis': 799,
 'Jaundice': 849,
 'Malaria': 899,
 'urinary tract infection': 949,
 'allergy': 999,
 'gastroesophageal reflux disease': 1049,
 'drug reaction': 1099,
 'peptic ulcer disease': 1149,
 'diabetes': 1199}

In [13]:
for i,label in enumerate(labels):
    labels[label] = i

In [14]:
labels

{'Psoriasis': 0,
 'Varicose Veins': 1,
 'Typhoid': 2,
 'Chicken pox': 3,
 'Impetigo': 4,
 'Dengue': 5,
 'Fungal infection': 6,
 'Common Cold': 7,
 'Pneumonia': 8,
 'Dimorphic Hemorrhoids': 9,
 'Arthritis': 10,
 'Acne': 11,
 'Bronchial Asthma': 12,
 'Hypertension': 13,
 'Migraine': 14,
 'Cervical spondylosis': 15,
 'Jaundice': 16,
 'Malaria': 17,
 'urinary tract infection': 18,
 'allergy': 19,
 'gastroesophageal reflux disease': 20,
 'drug reaction': 21,
 'peptic ulcer disease': 22,
 'diabetes': 23}

In [15]:
df['numeric_labels'] = df['label'].map(labels)

In [16]:
df

label                                               text  \
0     Psoriasis  I have been experiencing a skin rash on my arm...   
1     Psoriasis  My skin has been peeling, especially on my kne...   
2     Psoriasis  I have been experiencing joint pain in my fing...   
3     Psoriasis  There is a silver like dusting on my skin, esp...   
4     Psoriasis  My nails have small dents or pits in them, and...   
...         ...                                                ...   
1195   diabetes  I'm shaking and trembling all over. I've lost ...   
1196   diabetes  Particularly in the crevices of my skin, I hav...   
1197   diabetes  I regularly experience these intense urges and...   
1198   diabetes  I have trouble breathing, especially outside. ...   
1199   diabetes  I constantly sneeze and have a dry cough. My i...   

      numeric_labels  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
1195              23  
1196              23  
1197              23  
1198              23  
1199              23  

[1200 rows x 3 columns]

In [17]:
df = df[['text','numeric_labels']]

In [18]:
df

text  numeric_labels
0     I have been experiencing a skin rash on my arm...               0
1     My skin has been peeling, especially on my kne...               0
2     I have been experiencing joint pain in my fing...               0
3     There is a silver like dusting on my skin, esp...               0
4     My nails have small dents or pits in them, and...               0
...                                                 ...             ...
1195  I'm shaking and trembling all over. I've lost ...              23
1196  Particularly in the crevices of my skin, I hav...              23
1197  I regularly experience these intense urges and...              23
1198  I have trouble breathing, especially outside. ...              23
1199  I constantly sneeze and have a dry cough. My i...              23

[1200 rows x 2 columns]

In [19]:
nlp = spacy.load('en_core_web_lg')

In [33]:
X_train = []

for i,text in enumerate(df['text']):
    X_train.append(nlp(' '.join(tokenize(text))).vector)

In [34]:
X_train = np.array(X_train)

In [35]:
np.reshape(X_train, (X_train.shape[0], 1, -1))

array([[[-0.54754573,  1.5293411 , -3.1864688 , ..., -1.587846  ,
         -4.055408  ,  0.3511832 ]],

       [[-0.33694565,  1.157239  , -4.1838317 , ..., -2.1761875 ,
         -4.0750194 ,  0.53949636]],

       [[ 0.95211756,  1.2289593 , -3.0168636 , ..., -1.9683508 ,
         -4.2485194 ,  0.66581506]],

       ...,

       [[-0.01423497,  0.8064378 , -2.368547  , ..., -1.7864016 ,
         -6.402864  ,  1.3551161 ]],

       [[ 0.13563369,  1.4537063 , -3.4215791 , ..., -1.0420074 ,
         -4.1832013 ,  1.8470225 ]],

       [[ 0.73733205,  2.6833134 , -3.8056011 , ..., -0.81380695,
         -5.7926016 ,  1.7558377 ]]], dtype=float32)

In [36]:
X_train[0].shape

(300,)

In [39]:
X_train = np.reshape(X_train, (X_train.shape[0], 1, -1))

In [40]:
X_train[0].shape

(1, 300)

In [41]:
X_train = tf.convert_to_tensor(X_train)

In [42]:
X_train

<tf.Tensor: shape=(1200, 1, 300), dtype=float32, numpy=
array([[[-0.54754573,  1.5293411 , -3.1864688 , ..., -1.587846  ,
         -4.055408  ,  0.3511832 ]],

       [[-0.33694565,  1.157239  , -4.1838317 , ..., -2.1761875 ,
         -4.0750194 ,  0.53949636]],

       [[ 0.95211756,  1.2289593 , -3.0168636 , ..., -1.9683508 ,
         -4.2485194 ,  0.66581506]],

       ...,

       [[-0.01423497,  0.8064378 , -2.368547  , ..., -1.7864016 ,
         -6.402864  ,  1.3551161 ]],

       [[ 0.13563369,  1.4537063 , -3.4215791 , ..., -1.0420074 ,
         -4.1832013 ,  1.8470225 ]],

       [[ 0.73733205,  2.6833134 , -3.8056011 , ..., -0.81380695,
         -5.7926016 ,  1.7558377 ]]], dtype=float32)>

In [43]:
y_train = []

for i,label in enumerate(df['numeric_labels']):
    y_train.append(float(label))

In [44]:
y_train = np.array(y_train)

In [45]:
y_train

array([ 0.,  0.,  0., ..., 23., 23., 23.])

In [46]:
y_train = tf.convert_to_tensor(y_train)

In [47]:
y_train

<tf.Tensor: shape=(1200,), dtype=float64, numpy=array([ 0.,  0.,  0., ..., 23., 23., 23.])>

In [48]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [49]:
model = tf.keras.Sequential([
    tf.keras.layers.Conv1D(filters=64, kernel_size=1, activation='relu', input_shape=(1,300)),
    tf.keras.layers.GlobalMaxPooling1D(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(24, activation='softmax') 
])



model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

logdir = "logs/scalars/" + datetime.time().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = keras.callbacks.TensorBoard(log_dir=logdir)

model.fit(X_train, y_train, epochs=100, callbacks=[tensorboard_callback])


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)                    │ (None, 1, 64)               │          19,264 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_max_pooling1d_1               │ (None, 64)                  │               0 │
│ (GlobalMaxPooling1D)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 64)                  │           4,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 24)                  │           1,560 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 24,984 (97.59 KB)

 Trainable params: 24,984 (97.59 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.1049 - loss: 3.1962
Epoch 2/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.3167 - loss: 2.4998
Epoch 3/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4512 - loss: 2.0001
Epoch 4/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5727 - loss: 1.5191
Epoch 5/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6568 - loss: 1.2152
Epoch 6/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7047 - loss: 0.9977
Epoch 7/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7526 - loss: 0.8681
Epoch 8/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8224 - loss: 0.6837
Epoch 9/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8326 - loss: 0.6051
Epoch 10/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8660 - loss: 0.5403
Epoch 11/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8908 - loss: 0.4372
Epoch 12/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy:

In [50]:
sentence = df['text'].iloc[0]

In [57]:
sentence = "I've had a persistent skin rash on my arms, legs, and torso for a few weeks now. It appears as red, itchy patches, often covered in dry, scaly skin."

In [58]:
sentence = ' '.join(tokenize(sentence))
sentence = nlp(sentence).vector
sentence = np.reshape(sentence,(-1, 1, 300))
sentence = tf.convert_to_tensor(sentence)

In [59]:
sentence.shape

TensorShape([1, 1, 300])

In [60]:
prediction = model.predict(sentence)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step


In [61]:
prediction

array([[9.7917420e-01, 3.1168843e-06, 1.9131672e-11, 7.2154544e-05,
        1.2185176e-02, 2.9353448e-06, 8.0800317e-03, 7.5101081e-09,
        2.9105328e-16, 2.8120421e-11, 2.0696323e-08, 4.8013317e-04,
        6.9967122e-11, 2.1381793e-07, 1.7944260e-06, 3.6706274e-13,
        6.4409882e-08, 2.0165537e-14, 3.8077528e-09, 2.4533557e-08,
        2.0753598e-12, 3.7008923e-09, 3.3102778e-09, 2.1227816e-08]],
      dtype=float32)

In [62]:
np.argmax(prediction)

0

In [78]:
sent = """Lately I've been dealing with headaches, blurry vision, and digestive problems like heartburn and indigestion."""

In [79]:
sentence = ' '.join(tokenize(sent))
sentence = nlp(sentence).vector
sentence = np.reshape(sentence,(-1, 1, 300))
sentence = tf.convert_to_tensor(sentence)

In [80]:
sentence.shape

TensorShape([1, 1, 300])

In [81]:
prediction = model.predict(sentence)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


In [82]:
prediction

array([[1.6262225e-06, 4.5845760e-14, 7.3935458e-05, 2.0764700e-10,
        6.7354915e-14, 6.1586554e-09, 4.6783060e-11, 1.6473790e-07,
        1.4816022e-04, 2.6879849e-08, 6.0090814e-11, 7.2908923e-10,
        4.2922408e-09, 1.0046865e-02, 9.8964334e-01, 6.9102356e-08,
        1.5947026e-07, 7.0580121e-05, 5.0231241e-10, 2.1879595e-07,
        7.4105706e-13, 1.4803912e-05, 9.1258878e-10, 1.7751313e-09]],
      dtype=float32)

In [83]:
np.argmax(prediction)

14

In [84]:
%tensorboard --logdir logs

Reusing TensorBoard on port 6007 (pid 8000), started 1 day, 0:49:11 ago. (Use '!kill 8000' to kill it.)

In [85]:
model.save('D:\\HWAN\\Models\\Symptom_checker_Models\\SCM(Final).keras')